import type { Service } from "@/lib/types";

const CURRENT = "2026-09-02T09:00:00+05:00";

export const catalogSeedServices: Service[] = [
  {
    id: "service-silk-hall",
    sku: "MR-SVC-001",
    supplierId: "supplier-silk-road",
    categoryId: "cat-venue",
    title: "Банкетный зал Silk Hall",
    description: "Зал до 180 гостей, базовая мебель, сцена и парковка.",
    city: "Ташкент",
    priceFrom: 18_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/banquet.jpg",
    active: true,
    published: true,
    updatedAt: "2026-08-31T09:30:00+05:00",
    availabilityConfirmedAt: "2026-08-31T09:30:00+05:00",
  },
  {
    id: "service-silk-catering",
    sku: "MR-SVC-002",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Свадебный кейтеринг",
    description: "Меню узбекской и европейской кухни, обслуживание и сервировка.",
    city: "Ташкент",
    priceFrom: 240_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/catering.jpg",
    active: true,
    published: true,
    updatedAt: "2026-08-31T09:30:00+05:00",
    availabilityConfirmedAt: "2026-08-31T09:30:00+05:00",
  },
  {
    id: "service-nur-wedding",
    sku: "MR-SVC-003",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Фото + видео полного свадебного дня",
    description: "Два оператора, фотограф, короткий ролик и полный фильм.",
    city: "Ташкент",
    priceFrom: 8_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/photographer.jpg",
    active: true,
    published: true,
    updatedAt: "2026-08-28T16:10:00+05:00",
    availabilityConfirmedAt: "2026-08-28T16:10:00+05:00",
  },
  {
    id: "service-sabo-garden",
    sku: "MR-SVC-004",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Оформление Garden Wedding",
    description: "Концепция, президиум, флористика и фотозона.",
    city: "Самарканд",
    priceFrom: 12_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/decor.jpg",
    active: true,
    published: true,
    updatedAt: "2026-06-12T11:00:00+05:00",
    availabilityConfirmedAt: null,
  },
  {
    id: "service-teamcraft-day",
    sku: "MR-SVC-005",
    supplierId: "supplier-teamcraft",
    categoryId: "cat-training",
    title: "Командный день под ключ",
    description: "Диагностика запроса, сценарий, два фасилитатора и разбор результатов.",
    city: "Ташкент",
    priceFrom: 14_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/workshop.jpg",
    active: true,
    published: true,
    updatedAt: "2026-08-30T13:45:00+05:00",
    availabilityConfirmedAt: "2026-08-30T13:45:00+05:00",
  },
  {
    id: "service-silk-garden-ceremony",
    sku: "MR-SVC-006",
    supplierId: "supplier-silk-road",
    categoryId: "cat-venue",
    title: "Площадка для церемонии на открытом воздухе",
    description: "Зелёная площадка до 150 гостей, зона церемонии, электричество и парковка.",
    city: "Ташкент",
    priceFrom: 25_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/chairs.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-silk-conference-hall",
    sku: "MR-SVC-007",
    supplierId: "supplier-silk-road",
    categoryId: "cat-venue",
    title: "Конференц-зал для делового события",
    description: "Зал до 120 участников, сцена, экран, регистрационная зона и кофе-брейк по запросу.",
    city: "Ташкент",
    priceFrom: 12_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/banquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-silk-menu-standard",
    sku: "MR-SVC-008",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Свадебное меню — стандарт",
    description: "Горячее, салаты, закуски, напитки, сервировка и работа официантов.",
    city: "Ташкент",
    priceFrom: 390_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/catering.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-silk-menu-premium",
    sku: "MR-SVC-009",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Свадебное меню — расширенное",
    description: "Расширенное меню с несколькими горячими блюдами, десертами и полной сервировкой.",
    city: "Ташкент",
    priceFrom: 500_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/banquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-silk-coffee-break",
    sku: "MR-SVC-010",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Кофе-брейк для конференции",
    description: "Кофе, чай, вода, выпечка и лёгкие закуски с доставкой и сервировкой.",
    city: "Ташкент",
    priceFrom: 95_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/catering.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-nur-photo-four-hours",
    sku: "MR-SVC-011",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Фотограф на церемонию, 4 часа",
    description: "Репортаж церемонии и прогулки, цветокоррекция и готовая онлайн-галерея.",
    city: "Ташкент",
    priceFrom: 4_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/photographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-nur-video-full-day",
    sku: "MR-SVC-012",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Видеосъёмка полного свадебного дня",
    description: "Два оператора, запись ключевых моментов, короткий клип и фильм.",
    city: "Ташкент",
    priceFrom: 8_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/videographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-nur-drone",
    sku: "MR-SVC-013",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Съёмка с дрона и короткий ролик",
    description: "Воздушные кадры площадки и гостей, монтаж ролика до одной минуты.",
    city: "Ташкент",
    priceFrom: 3_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/videographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-nur-same-day-edit",
    sku: "MR-SVC-014",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Ролик в день мероприятия",
    description: "Съёмка и быстрый монтаж трёхминутного ролика для показа гостям в тот же вечер.",
    city: "Ташкент",
    priceFrom: 2_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/videographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sabo-photo-zone",
    sku: "MR-SVC-015",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Фотозона под ключ",
    description: "Эскиз, фон, надпись, простой декор, доставка, монтаж и демонтаж.",
    city: "Самарканд",
    priceFrom: 900_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/decor.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sabo-presidium",
    sku: "MR-SVC-016",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Оформление президиума молодожёнов",
    description: "Фон, стол молодожёнов, текстиль, композиции и мягкий свет.",
    city: "Самарканд",
    priceFrom: 2_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/decor.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sabo-wedding-100",
    sku: "MR-SVC-017",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Оформление свадьбы до 100 гостей",
    description: "Единая концепция, президиум, столы гостей, фотозона и монтаж команды.",
    city: "Самарканд",
    priceFrom: 12_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/banquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-host",
    sku: "MR-SVC-018",
    supplierId: "supplier-orzu",
    categoryId: "cat-host",
    title: "Ведущий на свадьбу",
    description: "Знакомство с парой, сценарный план, интерактивы без неловких конкурсов и ведение вечера.",
    city: "Ташкент",
    priceFrom: 5_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/host.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-host-dj",
    sku: "MR-SVC-019",
    supplierId: "supplier-orzu",
    categoryId: "cat-host",
    title: "Ведущий, DJ и базовый звук",
    description: "Ведущий, DJ, сценарный план, два микрофона и звуковой комплект для банкета.",
    city: "Ташкент",
    priceFrom: 10_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/host.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-ceremony-host",
    sku: "MR-SVC-020",
    supplierId: "supplier-orzu",
    categoryId: "cat-host",
    title: "Ведущий церемонии на русском и узбекском",
    description: "Короткая персональная церемония, согласованный текст и координация выходов пары.",
    city: "Ташкент",
    priceFrom: 3_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/microphone.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-dj",
    sku: "MR-SVC-021",
    supplierId: "supplier-orzu",
    categoryId: "cat-music",
    title: "DJ на свадебный вечер",
    description: "Музыкальный план, DJ-сет до шести часов и согласование стоп-листа заранее.",
    city: "Ташкент",
    priceFrom: 3_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/dj.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-live-band",
    sku: "MR-SVC-022",
    supplierId: "supplier-orzu",
    categoryId: "cat-music",
    title: "Живая группа на мероприятие",
    description: "Четыре музыканта, три концертных блока и заранее согласованный репертуар.",
    city: "Ташкент",
    priceFrom: 8_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-safar-sedan",
    sku: "MR-SVC-023",
    supplierId: "supplier-safar",
    categoryId: "cat-transport",
    title: "Свадебный седан с водителем",
    description: "Подача украшенного автомобиля, водитель и маршрут по городу до восьми часов.",
    city: "Ташкент",
    priceFrom: 2_500_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-car.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-safar-minibus",
    sku: "MR-SVC-024",
    supplierId: "supplier-safar",
    categoryId: "cat-transport",
    title: "Микроавтобус для гостей",
    description: "Трансфер до 18 гостей по согласованному маршруту с ожиданием у площадки.",
    city: "Ташкент",
    priceFrom: 2_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-car.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-teamcraft-strategy",
    sku: "MR-SVC-025",
    supplierId: "supplier-teamcraft",
    categoryId: "cat-training",
    title: "Стратегическая сессия для команды",
    description: "Подготовительные интервью, рабочая сессия до 20 участников и протокол решений.",
    city: "Ташкент",
    priceFrom: 12_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/workshop.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-teamcraft-outdoor",
    sku: "MR-SVC-026",
    supplierId: "supplier-teamcraft",
    categoryId: "cat-training",
    title: "Выездной тимбилдинг",
    description: "Сценарий для команды до 50 человек, ведущие, реквизит и итоговый разбор.",
    city: "Ташкент",
    priceFrom: 9_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/workshop.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-bouquet",
    sku: "MR-MKT-001",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Свадебный букет из сезонных цветов",
    description: "Букет невесты в выбранной гамме, лента и упаковка для перевозки.",
    city: "Ташкент",
    priceFrom: 650_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/bouquet.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-gulzor-candles",
    sku: "MR-MKT-002",
    supplierId: "supplier-gulzor",
    categoryId: "cat-event-details",
    title: "Набор свечей и подсвечников для столов",
    description: "Готовый набор для оформления пяти гостевых столов в тёплой гамме.",
    city: "Ташкент",
    priceFrom: 480_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/decor.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-gulzor-invitations",
    sku: "MR-MKT-003",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Именные приглашения, 50 штук",
    description: "Дизайн, печать и конверты; текст согласуется до запуска в производство.",
    city: "Ташкент",
    priceFrom: 900_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-gulzor-white-bouquet",
    sku: "MR-MKT-004",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Белый букет невесты",
    description: "Светлые розы и сезонная зелень, лента и защитная упаковка для перевозки.",
    city: "Ташкент",
    priceFrom: 750_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/bouquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-table-flowers",
    sku: "MR-MKT-005",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Цветочная композиция на стол",
    description: "Низкая композиция из сезонных цветов, которая не закрывает гостям обзор.",
    city: "Ташкент",
    priceFrom: 180_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/banquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-boutonniere",
    sku: "MR-MKT-006",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Бутоньерки для жениха и свидетелей",
    description: "Пять бутоньерок в стиле букета невесты, крепления и коробка для перевозки.",
    city: "Ташкент",
    priceFrom: 300_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/bouquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-seating-plan",
    sku: "MR-MKT-007",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Приветственная табличка и план рассадки",
    description: "Два макета в едином стиле, печать на твёрдой основе и проверка списка гостей.",
    city: "Ташкент",
    priceFrom: 650_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-guest-gifts",
    sku: "MR-MKT-008",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Именные подарки гостям, 50 штук",
    description: "Небольшие коробочки с персональной карточкой; наполнение выбирается при заказе.",
    city: "Ташкент",
    priceFrom: 1_250_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-invitations-premium",
    sku: "MR-MKT-009",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Приглашения с конвертами, 100 штук",
    description: "Персональный макет, плотная бумага, конверты и печать имён гостей.",
    city: "Ташкент",
    priceFrom: 1_800_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-shirin-wedding-cake",
    sku: "MR-MKT-010",
    supplierId: "supplier-shirin",
    categoryId: "cat-cakes",
    title: "Свадебный торт с оформлением",
    description: "Начинка на выбор, выравнивание, простой цветочный декор и согласованный вес.",
    city: "Ташкент",
    priceFrom: 190_000,
    priceUnit: "за килограмм",
    offerKind: "sale",
    imageUrl: "/catalog/photos/cake.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-shirin-candy-bar",
    sku: "MR-MKT-011",
    supplierId: "supplier-shirin",
    categoryId: "cat-cakes",
    title: "Сладкий стол на 30 гостей",
    description: "Капкейки, порционные десерты, подставки и карточки с названиями.",
    city: "Ташкент",
    priceFrom: 1_200_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/cake.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-ovoza-sound",
    sku: "MR-EQP-001",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Комплект звука и света для зала",
    description: "Колонки, микрофоны, световые приборы, доставка и настройка перед событием.",
    city: "Ташкент",
    priceFrom: 4_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/audio.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-led",
    sku: "MR-EQP-002",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-screens-stage",
    title: "LED-экран с установкой",
    description: "Экран подходящего размера, доставка, монтаж, проверка и демонтаж после события.",
    city: "Ташкент",
    priceFrom: 7_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-engineer",
    sku: "MR-EQP-003",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Технический специалист на мероприятие",
    description: "Настройка оборудования и контроль звука и света во время программы.",
    city: "Ташкент",
    priceFrom: 1_600_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/audio.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-garland",
    sku: "MR-EQP-004",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Гирлянда тёплого света, 20 метров",
    description: "Соединяемая уличная гирлянда для фотозоны, навеса или небольшого зала.",
    city: "Ташкент",
    priceFrom: 780_000,
    priceUnit: "за комплект",
    offerKind: "sale",
    imageUrl: "/catalog/photos/decor.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-wireless-mics",
    sku: "MR-EQP-005",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Два беспроводных микрофона",
    description: "Два ручных микрофона, приёмник, стойка, кабели и проверка перед выдачей.",
    city: "Ташкент",
    priceFrom: 350_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/microphone.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-ovoza-projector",
    sku: "MR-EQP-006",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-screens-stage",
    title: "Проектор и экран для презентации",
    description: "Проектор, экран на стойке, кабели, доставка и настройка изображения.",
    city: "Ташкент",
    priceFrom: 1_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-ovoza-conference-kit",
    sku: "MR-EQP-007",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-screens-stage",
    title: "Комплект для видеоконференции",
    description: "Камера, микрофоны, колонки, видеомикшер, коммутация и техническая настройка.",
    city: "Ташкент",
    priceFrom: 1_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/videographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-ovoza-stage-light",
    sku: "MR-EQP-008",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Сценический свет для небольшого зала",
    description: "Восемь световых приборов, стойки, контроллер, доставка и базовая настройка.",
    city: "Ташкент",
    priceFrom: 2_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sahna-stage",
    sku: "MR-EQP-009",
    supplierId: "supplier-sahna",
    categoryId: "cat-screens-stage",
    title: "Сцена 6 × 4 метра с монтажом",
    description: "Модульный подиум, лестница, юбка сцены, доставка, монтаж и демонтаж.",
    city: "Ташкент",
    priceFrom: 3_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sahna-furniture-50",
    sku: "MR-EQP-010",
    supplierId: "supplier-sahna",
    categoryId: "cat-event-rental",
    title: "Столы и стулья на 50 гостей",
    description: "Пять круглых столов, 50 стульев, доставка и сбор после мероприятия.",
    city: "Ташкент",
    priceFrom: 2_500_000,
    priceUnit: "за комплект",
    offerKind: "rental",
    imageUrl: "/catalog/photos/chairs.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sahna-tent",
    sku: "MR-EQP-011",
    supplierId: "supplier-sahna",
    categoryId: "cat-event-rental",
    title: "Шатёр для события с монтажом",
    description: "Защитный шатёр для открытой площадки, доставка, монтаж и крепление конструкции.",
    city: "Ташкент",
    priceFrom: 2_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/chairs.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
];

