import type { Service } from "@/lib/types";

const CURRENT = "2026-09-02T09:00:00+05:00";

type CurrentSeedOffer = Pick<
  Service,
  | "id"
  | "sku"
  | "supplierId"
  | "categoryId"
  | "title"
  | "description"
  | "city"
  | "priceFrom"
  | "priceUnit"
  | "offerKind"
  | "imageUrl"
>;

function currentSeedOffer(offer: CurrentSeedOffer): Service {
  return {
    ...offer,
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  };
}

export const catalogSeedServices: Service[] = [
  {
    id: "service-silk-hall",
    sku: "MR-SVC-001",
    supplierId: "supplier-silk-road",
    categoryId: "cat-venue",
    title: "Банкетный зал Silk Hall",
    description: "Зал до 180 гостей, базовая мебель, сцена и парковка.",
    city: "Ташкент",
    priceFrom: 18_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/banquet.jpg",
    active: true,
    published: true,
    updatedAt: "2026-08-31T09:30:00+05:00",
    availabilityConfirmedAt: "2026-08-31T09:30:00+05:00",
  },
  {
    id: "service-silk-catering",
    sku: "MR-SVC-002",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Свадебный кейтеринг",
    description: "Меню узбекской и европейской кухни, обслуживание и сервировка.",
    city: "Ташкент",
    priceFrom: 240_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/catering.jpg",
    active: true,
    published: true,
    updatedAt: "2026-08-31T09:30:00+05:00",
    availabilityConfirmedAt: "2026-08-31T09:30:00+05:00",
  },
  {
    id: "service-nur-wedding",
    sku: "MR-SVC-003",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Фото + видео полного свадебного дня",
    description: "Два оператора, фотограф, короткий ролик и полный фильм.",
    city: "Ташкент",
    priceFrom: 8_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/photographer.jpg",
    active: true,
    published: true,
    updatedAt: "2026-08-28T16:10:00+05:00",
    availabilityConfirmedAt: "2026-08-28T16:10:00+05:00",
  },
  {
    id: "service-sabo-garden",
    sku: "MR-SVC-004",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Оформление Garden Wedding",
    description: "Концепция, президиум, флористика и фотозона.",
    city: "Самарканд",
    priceFrom: 12_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/garden-night.jpg",
    active: true,
    published: true,
    updatedAt: "2026-06-12T11:00:00+05:00",
    availabilityConfirmedAt: null,
  },
  {
    id: "service-teamcraft-day",
    sku: "MR-SVC-005",
    supplierId: "supplier-teamcraft",
    categoryId: "cat-training",
    title: "Командный день под ключ",
    description: "Диагностика запроса, сценарий, два фасилитатора и разбор результатов.",
    city: "Ташкент",
    priceFrom: 14_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/workshop.jpg",
    active: true,
    published: true,
    updatedAt: "2026-08-30T13:45:00+05:00",
    availabilityConfirmedAt: "2026-08-30T13:45:00+05:00",
  },
  {
    id: "service-silk-garden-ceremony",
    sku: "MR-SVC-006",
    supplierId: "supplier-silk-road",
    categoryId: "cat-venue",
    title: "Площадка для церемонии на открытом воздухе",
    description: "Зелёная площадка до 150 гостей, зона церемонии, электричество и парковка.",
    city: "Ташкент",
    priceFrom: 25_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/chairs.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-silk-conference-hall",
    sku: "MR-SVC-007",
    supplierId: "supplier-silk-road",
    categoryId: "cat-venue",
    title: "Конференц-зал для делового события",
    description: "Зал до 120 участников, сцена, экран, регистрационная зона и кофе-брейк по запросу.",
    city: "Ташкент",
    priceFrom: 12_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/venue-luxury.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-silk-menu-standard",
    sku: "MR-SVC-008",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Свадебное меню — стандарт",
    description: "Горячее, салаты, закуски, напитки, сервировка и работа официантов.",
    city: "Ташкент",
    priceFrom: 390_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/catering.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-silk-menu-premium",
    sku: "MR-SVC-009",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Свадебное меню — расширенное",
    description: "Расширенное меню с несколькими горячими блюдами, десертами и полной сервировкой.",
    city: "Ташкент",
    priceFrom: 500_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/buffet-luxury.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-silk-coffee-break",
    sku: "MR-SVC-010",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Кофе-брейк для конференции",
    description: "Кофе, чай, вода, выпечка и лёгкие закуски с доставкой и сервировкой.",
    city: "Ташкент",
    priceFrom: 95_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/catering.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-nur-photo-four-hours",
    sku: "MR-SVC-011",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Фотограф на церемонию, 4 часа",
    description: "Репортаж церемонии и прогулки, цветокоррекция и готовая онлайн-галерея.",
    city: "Ташкент",
    priceFrom: 4_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/photographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-nur-video-full-day",
    sku: "MR-SVC-012",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Видеосъёмка полного свадебного дня",
    description: "Два оператора, запись ключевых моментов, короткий клип и фильм.",
    city: "Ташкент",
    priceFrom: 8_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/videographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-nur-drone",
    sku: "MR-SVC-013",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Съёмка с дрона и короткий ролик",
    description: "Воздушные кадры площадки и гостей, монтаж ролика до одной минуты.",
    city: "Ташкент",
    priceFrom: 3_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/videographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-nur-same-day-edit",
    sku: "MR-SVC-014",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Ролик в день мероприятия",
    description: "Съёмка и быстрый монтаж трёхминутного ролика для показа гостям в тот же вечер.",
    city: "Ташкент",
    priceFrom: 2_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/videographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sabo-photo-zone",
    sku: "MR-SVC-015",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Фотозона под ключ",
    description: "Эскиз, фон, надпись, простой декор, доставка, монтаж и демонтаж.",
    city: "Самарканд",
    priceFrom: 900_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/market-decor-photozone.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sabo-presidium",
    sku: "MR-SVC-016",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Оформление президиума молодожёнов",
    description: "Фон, стол молодожёнов, текстиль, композиции и мягкий свет.",
    city: "Самарканд",
    priceFrom: 2_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/market-decor-stage.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sabo-wedding-100",
    sku: "MR-SVC-017",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Оформление свадьбы до 100 гостей",
    description: "Единая концепция, президиум, столы гостей, фотозона и монтаж команды.",
    city: "Самарканд",
    priceFrom: 12_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/market-decor-table.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-host",
    sku: "MR-SVC-018",
    supplierId: "supplier-orzu",
    categoryId: "cat-host",
    title: "Ведущий на свадьбу",
    description: "Знакомство с парой, сценарный план, интерактивы без неловких конкурсов и ведение вечера.",
    city: "Ташкент",
    priceFrom: 5_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/host.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-host-dj",
    sku: "MR-SVC-019",
    supplierId: "supplier-orzu",
    categoryId: "cat-host",
    title: "Ведущий, DJ и базовый звук",
    description: "Ведущий, DJ, сценарный план, два микрофона и звуковой комплект для банкета.",
    city: "Ташкент",
    priceFrom: 10_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/host.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-ceremony-host",
    sku: "MR-SVC-020",
    supplierId: "supplier-orzu",
    categoryId: "cat-host",
    title: "Ведущий церемонии на русском и узбекском",
    description: "Короткая персональная церемония, согласованный текст и координация выходов пары.",
    city: "Ташкент",
    priceFrom: 3_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/microphone.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-dj",
    sku: "MR-SVC-021",
    supplierId: "supplier-orzu",
    categoryId: "cat-music",
    title: "DJ на свадебный вечер",
    description: "Музыкальный план, DJ-сет до шести часов и согласование стоп-листа заранее.",
    city: "Ташкент",
    priceFrom: 3_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/dj.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-orzu-live-band",
    sku: "MR-SVC-022",
    supplierId: "supplier-orzu",
    categoryId: "cat-music",
    title: "Живая группа на мероприятие",
    description: "Четыре музыканта, три концертных блока и заранее согласованный репертуар.",
    city: "Ташкент",
    priceFrom: 8_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-safar-sedan",
    sku: "MR-SVC-023",
    supplierId: "supplier-safar",
    categoryId: "cat-transport",
    title: "Свадебный седан с водителем",
    description: "Подача украшенного автомобиля, водитель и маршрут по городу до восьми часов.",
    city: "Ташкент",
    priceFrom: 2_500_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-car.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-safar-minibus",
    sku: "MR-SVC-024",
    supplierId: "supplier-safar",
    categoryId: "cat-transport",
    title: "Микроавтобус для гостей",
    description: "Трансфер до 18 гостей по согласованному маршруту с ожиданием у площадки.",
    city: "Ташкент",
    priceFrom: 2_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-car.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-teamcraft-strategy",
    sku: "MR-SVC-025",
    supplierId: "supplier-teamcraft",
    categoryId: "cat-training",
    title: "Стратегическая сессия для команды",
    description: "Подготовительные интервью, рабочая сессия до 20 участников и протокол решений.",
    city: "Ташкент",
    priceFrom: 12_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/workshop.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-teamcraft-outdoor",
    sku: "MR-SVC-026",
    supplierId: "supplier-teamcraft",
    categoryId: "cat-training",
    title: "Выездной тимбилдинг",
    description: "Сценарий для команды до 50 человек, ведущие, реквизит и итоговый разбор.",
    city: "Ташкент",
    priceFrom: 9_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/team-game.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-bouquet",
    sku: "MR-MKT-001",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Свадебный букет из сезонных цветов",
    description: "Букет невесты в выбранной гамме, лента и упаковка для перевозки.",
    city: "Ташкент",
    priceFrom: 650_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/bouquet.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-gulzor-candles",
    sku: "MR-MKT-002",
    supplierId: "supplier-gulzor",
    categoryId: "cat-event-details",
    title: "Набор свечей и подсвечников для столов",
    description: "Готовый набор для оформления пяти гостевых столов в тёплой гамме.",
    city: "Ташкент",
    priceFrom: 480_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/decor.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-gulzor-invitations",
    sku: "MR-MKT-003",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Именные приглашения, 50 штук",
    description: "Дизайн, печать и конверты; текст согласуется до запуска в производство.",
    city: "Ташкент",
    priceFrom: 900_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-gulzor-white-bouquet",
    sku: "MR-MKT-004",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Белый букет невесты",
    description: "Светлые розы и сезонная зелень, лента и защитная упаковка для перевозки.",
    city: "Ташкент",
    priceFrom: 750_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/bouquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-table-flowers",
    sku: "MR-MKT-005",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Цветочная композиция на стол",
    description: "Низкая композиция из сезонных цветов, которая не закрывает гостям обзор.",
    city: "Ташкент",
    priceFrom: 180_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/banquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-boutonniere",
    sku: "MR-MKT-006",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Бутоньерки для жениха и свидетелей",
    description: "Пять бутоньерок в стиле букета невесты, крепления и коробка для перевозки.",
    city: "Ташкент",
    priceFrom: 300_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/bouquet.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-seating-plan",
    sku: "MR-MKT-007",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Приветственная табличка и план рассадки",
    description: "Два макета в едином стиле, печать на твёрдой основе и проверка списка гостей.",
    city: "Ташкент",
    priceFrom: 650_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-guest-gifts",
    sku: "MR-MKT-008",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Именные подарки гостям, 50 штук",
    description: "Небольшие коробочки с персональной карточкой; наполнение выбирается при заказе.",
    city: "Ташкент",
    priceFrom: 1_250_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-gulzor-invitations-premium",
    sku: "MR-MKT-009",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Приглашения с конвертами, 100 штук",
    description: "Персональный макет, плотная бумага, конверты и печать имён гостей.",
    city: "Ташкент",
    priceFrom: 1_800_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-shirin-wedding-cake",
    sku: "MR-MKT-010",
    supplierId: "supplier-shirin",
    categoryId: "cat-cakes",
    title: "Свадебный торт с оформлением",
    description: "Начинка на выбор, выравнивание, простой цветочный декор и согласованный вес.",
    city: "Ташкент",
    priceFrom: 190_000,
    priceUnit: "за килограмм",
    offerKind: "sale",
    imageUrl: "/catalog/photos/cake.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-shirin-candy-bar",
    sku: "MR-MKT-011",
    supplierId: "supplier-shirin",
    categoryId: "cat-cakes",
    title: "Сладкий стол на 30 гостей",
    description: "Капкейки, порционные десерты, подставки и карточки с названиями.",
    city: "Ташкент",
    priceFrom: 1_200_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/cake.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-ovoza-sound",
    sku: "MR-EQP-001",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Комплект звука и света для зала",
    description: "Колонки, микрофоны, световые приборы, доставка и настройка перед событием.",
    city: "Ташкент",
    priceFrom: 4_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/sound-mixer-event.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-led",
    sku: "MR-EQP-002",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-screens-stage",
    title: "LED-экран с установкой",
    description: "Экран подходящего размера, доставка, монтаж, проверка и демонтаж после события.",
    city: "Ташкент",
    priceFrom: 7_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-engineer",
    sku: "MR-EQP-003",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Технический специалист на мероприятие",
    description: "Настройка оборудования и контроль звука и света во время программы.",
    city: "Ташкент",
    priceFrom: 1_600_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/audio.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-garland",
    sku: "MR-EQP-004",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Гирлянда тёплого света, 20 метров",
    description: "Соединяемая уличная гирлянда для фотозоны, навеса или небольшого зала.",
    city: "Ташкент",
    priceFrom: 780_000,
    priceUnit: "за комплект",
    offerKind: "sale",
    imageUrl: "/catalog/photos/decor.jpg",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-wireless-mics",
    sku: "MR-EQP-005",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Два беспроводных микрофона",
    description: "Два ручных микрофона, приёмник, стойка, кабели и проверка перед выдачей.",
    city: "Ташкент",
    priceFrom: 350_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/microphone.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-ovoza-projector",
    sku: "MR-EQP-006",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-screens-stage",
    title: "Проектор и экран для презентации",
    description: "Проектор, экран на стойке, кабели, доставка и настройка изображения.",
    city: "Ташкент",
    priceFrom: 1_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/market-projector.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-ovoza-conference-kit",
    sku: "MR-EQP-007",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-screens-stage",
    title: "Комплект для видеоконференции",
    description: "Камера, микрофоны, колонки, видеомикшер, коммутация и техническая настройка.",
    city: "Ташкент",
    priceFrom: 1_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/videographer.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-ovoza-stage-light",
    sku: "MR-EQP-008",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Сценический свет для небольшого зала",
    description: "Восемь световых приборов, стойки, контроллер, доставка и базовая настройка.",
    city: "Ташкент",
    priceFrom: 2_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sahna-stage",
    sku: "MR-EQP-009",
    supplierId: "supplier-sahna",
    categoryId: "cat-screens-stage",
    title: "Сцена 6 × 4 метра с монтажом",
    description: "Модульный подиум, лестница, юбка сцены, доставка, монтаж и демонтаж.",
    city: "Ташкент",
    priceFrom: 3_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/stage.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sahna-furniture-50",
    sku: "MR-EQP-010",
    supplierId: "supplier-sahna",
    categoryId: "cat-event-rental",
    title: "Столы и стулья на 50 гостей",
    description: "Пять круглых столов, 50 стульев, доставка и сбор после мероприятия.",
    city: "Ташкент",
    priceFrom: 2_500_000,
    priceUnit: "за комплект",
    offerKind: "rental",
    imageUrl: "/catalog/photos/chairs.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  {
    id: "service-sahna-tent",
    sku: "MR-EQP-011",
    supplierId: "supplier-sahna",
    categoryId: "cat-event-rental",
    title: "Шатёр для события с монтажом",
    description: "Защитный шатёр для открытой площадки, доставка, монтаж и крепление конструкции.",
    city: "Ташкент",
    priceFrom: 2_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/chairs.jpg",
    active: true,
    published: true,
    updatedAt: CURRENT,
    availabilityConfirmedAt: CURRENT,
  },
  currentSeedOffer({
    id: "service-zarafshon-nikoh-hall",
    sku: "MR-SVC-027",
    supplierId: "supplier-zarafshon",
    categoryId: "cat-venue",
    title: "Зал для никаха и семейного ужина",
    description: "Камерный зал до 60 гостей, отдельная зона церемонии, мебель и базовая сервировка.",
    city: "Бухара",
    priceFrom: 8_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/venue-round-tables.jpg",
  }),
  currentSeedOffer({
    id: "service-zarafshon-terrace",
    sku: "MR-SVC-028",
    supplierId: "supplier-zarafshon",
    categoryId: "cat-venue",
    title: "Терраса для выездной церемонии",
    description: "Открытая площадка до 100 гостей, навес, свет, зона встречи и резерв на случай дождя.",
    city: "Бухара",
    priceFrom: 14_000_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-terrace.jpg",
  }),
  currentSeedOffer({
    id: "service-silk-business-room",
    sku: "MR-SVC-029",
    supplierId: "supplier-silk-road",
    categoryId: "cat-venue",
    title: "Переговорный зал для тренинга",
    description: "Зал до 35 участников, мобильная рассадка, экран, флипчарт и вода.",
    city: "Ташкент",
    priceFrom: 4_500_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/conference-room.jpg",
  }),
  currentSeedOffer({
    id: "service-nur-photo-location",
    sku: "MR-SVC-030",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Фотолокация для пары, 2 часа",
    description: "Подготовленная интерьерная площадка, свет и помощь фотографа с позированием.",
    city: "Ташкент",
    priceFrom: 1_400_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-couple.jpg",
  }),
  currentSeedOffer({
    id: "service-zarafshon-plov-station",
    sku: "MR-SVC-031",
    supplierId: "supplier-zarafshon",
    categoryId: "cat-catering",
    title: "Плов-станция для 100 гостей",
    description: "Приготовление на площадке, порционная подача, салаты, лепёшки и работа поваров.",
    city: "Бухара",
    priceFrom: 12_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/buffet-outdoor.jpg",
  }),
  currentSeedOffer({
    id: "service-fergana-family-menu",
    sku: "MR-SVC-032",
    supplierId: "supplier-fergana-party",
    categoryId: "cat-catering",
    title: "Семейное меню для 30 гостей",
    description: "Горячие блюда, салаты, фрукты и безалкогольные напитки с доставкой и сервировкой.",
    city: "Фергана",
    priceFrom: 6_600_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-buffet.jpg",
  }),
  currentSeedOffer({
    id: "service-silk-welcome-drinks",
    sku: "MR-SVC-033",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Welcome-бар без алкоголя",
    description: "Лимонады, вода, сезонные фрукты, лёд, посуда и два сотрудника на встрече гостей.",
    city: "Ташкент",
    priceFrom: 85_000,
    priceUnit: "за гостя",
    offerKind: "service",
    imageUrl: "/catalog/photos/catering-wedding.jpg",
  }),
  currentSeedOffer({
    id: "service-nur-love-story",
    sku: "MR-SVC-034",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-marry-me",
    title: "Предложение руки и сердца + Love story",
    description: "Личный сценарий, подбор локации, координация сюрприза и 40 обработанных фотографий.",
    city: "Ташкент",
    priceFrom: 2_200_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-couple.jpg",
  }),
  currentSeedOffer({
    id: "service-nur-studio-portraits",
    sku: "MR-SVC-035",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Студийные портреты пары",
    description: "Студия, импульсный свет, помощь с позированием и 25 готовых кадров.",
    city: "Ташкент",
    priceFrom: 1_600_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/photographer.jpg",
  }),
  currentSeedOffer({
    id: "service-nur-vertical-clips",
    sku: "MR-SVC-036",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Вертикальные видео в день события",
    description: "Мобильная съёмка гостей и деталей, пять коротких роликов для социальных сетей.",
    city: "Ташкент",
    priceFrom: 1_800_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/videographer.jpg",
  }),
  currentSeedOffer({
    id: "service-nur-livestream",
    sku: "MR-SVC-037",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Прямая трансляция церемонии",
    description: "Две камеры, звук с площадки, закрытая ссылка и запись эфира после события.",
    city: "Ташкент",
    priceFrom: 4_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/conference-av.jpg",
  }),
  currentSeedOffer({
    id: "service-sabo-floral-arch",
    sku: "MR-SVC-038",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Цветочная арка для церемонии",
    description: "Каркас, текстиль, композиции из живых и декоративных цветов, монтаж и демонтаж.",
    city: "Самарканд",
    priceFrom: 3_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/decor-floral.jpg",
  }),
  currentSeedOffer({
    id: "service-fergana-balloon-zone",
    sku: "MR-SVC-039",
    supplierId: "supplier-fergana-party",
    categoryId: "cat-decor",
    title: "Фотозона из шаров",
    description: "Арка из шаров, фон, имя или надпись, доставка и монтаж на семейный праздник.",
    city: "Фергана",
    priceFrom: 700_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/market-decor-arch.jpg",
  }),
  currentSeedOffer({
    id: "service-sabo-table-decor",
    sku: "MR-SVC-040",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Оформление десяти гостевых столов",
    description: "Текстиль, свечи, номера столов и низкие композиции с монтажом до прихода гостей.",
    city: "Самарканд",
    priceFrom: 4_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/decor-table.jpg",
  }),
  currentSeedOffer({
    id: "service-fergana-ceremony-coordinator",
    sku: "MR-SVC-041",
    supplierId: "supplier-fergana-party",
    categoryId: "cat-planning",
    title: "Координатор свадебной церемонии",
    description: "Тайминг, сбор подрядчиков, контроль выходов пары и решение вопросов на площадке.",
    city: "Фергана",
    priceFrom: 2_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/event-coordinator.jpg",
  }),
  currentSeedOffer({
    id: "service-fergana-female-host",
    sku: "MR-SVC-042",
    supplierId: "supplier-fergana-party",
    categoryId: "cat-host",
    title: "Ведущая на русском и узбекском",
    description: "Знакомство с семьёй, согласованный сценарий и ведение программы до пяти часов.",
    city: "Фергана",
    priceFrom: 3_800_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/host.jpg",
  }),
  currentSeedOffer({
    id: "service-fergana-animators",
    sku: "MR-SVC-043",
    supplierId: "supplier-fergana-party",
    categoryId: "cat-host",
    title: "Два аниматора для детского праздника",
    description: "Игровая программа на 90 минут, простой реквизит и музыкальное сопровождение.",
    city: "Фергана",
    priceFrom: 1_200_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/decor-balloon.jpg",
  }),
  currentSeedOffer({
    id: "service-zarafshon-national-ensemble",
    sku: "MR-SVC-044",
    supplierId: "supplier-zarafshon",
    categoryId: "cat-music",
    title: "Ансамбль национальной музыки",
    description: "Три музыканта, встреча гостей и два концертных блока по согласованной программе.",
    city: "Бухара",
    priceFrom: 4_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/stage.jpg",
  }),
  currentSeedOffer({
    id: "service-orzu-saxophone",
    sku: "MR-SVC-045",
    supplierId: "supplier-orzu",
    categoryId: "cat-music",
    title: "Саксофонист на встречу гостей",
    description: "Живой сет до 60 минут, фонограммы и согласование музыкального настроения заранее.",
    city: "Ташкент",
    priceFrom: 2_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/saxophone.jpg",
  }),
  currentSeedOffer({
    id: "service-safar-premium-car",
    sku: "MR-SVC-046",
    supplierId: "supplier-safar",
    categoryId: "cat-transport",
    title: "Автомобиль бизнес-класса с водителем",
    description: "Чистый автомобиль, подача по адресу и городской маршрут пары до шести часов.",
    city: "Ташкент",
    priceFrom: 3_200_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/luxury-car.jpg",
  }),
  currentSeedOffer({
    id: "service-safar-guest-bus",
    sku: "MR-SVC-047",
    supplierId: "supplier-safar",
    categoryId: "cat-transport",
    title: "Автобус для 45 гостей",
    description: "Подача к месту сбора, поездка до площадки и обратный трансфер после программы.",
    city: "Ташкент",
    priceFrom: 3_500_000,
    priceUnit: "за день",
    offerKind: "service",
    imageUrl: "/catalog/photos/wedding-car.jpg",
  }),
  currentSeedOffer({
    id: "service-safar-airport-transfer",
    sku: "MR-SVC-048",
    supplierId: "supplier-safar",
    categoryId: "cat-transport",
    title: "Встреча гостей в аэропорту",
    description: "Табличка с именем, ожидание рейса и доставка до гостиницы или места события.",
    city: "Ташкент",
    priceFrom: 450_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/luxury-car.jpg",
  }),
  currentSeedOffer({
    id: "service-yuksalish-leadership",
    sku: "MR-SVC-049",
    supplierId: "supplier-yuksalish",
    categoryId: "cat-training",
    title: "Практикум для руководителей",
    description: "Однодневная программа до 20 участников, рабочая тетрадь и план действий команды.",
    city: "Ташкент",
    priceFrom: 11_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/conference-speaker.jpg",
  }),
  currentSeedOffer({
    id: "service-yuksalish-sales",
    sku: "MR-SVC-050",
    supplierId: "supplier-yuksalish",
    categoryId: "cat-training",
    title: "Тренинг переговоров и продаж",
    description: "Предварительный созвон, шесть часов практики, ролевые ситуации и рекомендации руководителю.",
    city: "Ташкент",
    priceFrom: 9_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/conference-presentation.jpg",
  }),
  currentSeedOffer({
    id: "service-yuksalish-indoor-game",
    sku: "MR-SVC-051",
    supplierId: "supplier-yuksalish",
    categoryId: "cat-training",
    title: "Командная игра в помещении",
    description: "Сценарий на два часа, фасилитатор, реквизит и короткое обсуждение результата.",
    city: "Ташкент",
    priceFrom: 5_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/team-trust.jpg",
  }),
  currentSeedOffer({
    id: "service-yuksalish-outdoor-quest",
    sku: "MR-SVC-052",
    supplierId: "supplier-yuksalish",
    categoryId: "cat-training",
    title: "Выездной командный квест",
    description: "Маршрут, задания, ведущие и реквизит для команды до 60 человек.",
    city: "Ташкент",
    priceFrom: 8_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/team-grid.jpg",
  }),
  currentSeedOffer({
    id: "service-yuksalish-registration-team",
    sku: "MR-SVC-053",
    supplierId: "supplier-yuksalish",
    categoryId: "cat-planning",
    title: "Команда регистрации на конференцию",
    description: "Два администратора, списки гостей, бейджи и встреча участников до начала программы.",
    city: "Ташкент",
    priceFrom: 1_800_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/event-registration.jpg",
  }),
  currentSeedOffer({
    id: "service-yuksalish-event-manager",
    sku: "MR-SVC-054",
    supplierId: "supplier-yuksalish",
    categoryId: "cat-planning",
    title: "Менеджер события на площадке",
    description: "Единая точка связи для подрядчиков, контроль тайминга и отчёт после завершения.",
    city: "Ташкент",
    priceFrom: 3_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    imageUrl: "/catalog/photos/event-coordinator.jpg",
  }),
  currentSeedOffer({
    id: "service-gulzor-premium-bouquet",
    sku: "MR-MKT-012",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Объёмный букет невесты",
    description: "Розы, сезонные цветы и зелень в согласованной палитре, лента и упаковка.",
    city: "Ташкент",
    priceFrom: 1_200_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/bouquet.jpg",
  }),
  currentSeedOffer({
    id: "service-gulzor-mini-bouquets",
    sku: "MR-MKT-013",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Мини-букеты для подруг невесты",
    description: "Три небольших букета в стиле основного букета, ленты и коробка для перевозки.",
    city: "Ташкент",
    priceFrom: 750_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/decor-floral.jpg",
  }),
  currentSeedOffer({
    id: "service-fergana-artificial-flowers",
    sku: "MR-MKT-014",
    supplierId: "supplier-fergana-party",
    categoryId: "cat-flowers",
    title: "Набор декоративных цветов для арки",
    description: "Многоразовые цветочные ветви в светлой гамме для самостоятельного оформления.",
    city: "Фергана",
    priceFrom: 980_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/gift-floral.jpg",
  }),
  currentSeedOffer({
    id: "service-gulzor-table-runners",
    sku: "MR-MKT-015",
    supplierId: "supplier-gulzor",
    categoryId: "cat-event-details",
    title: "Дорожки для столов, 10 штук",
    description: "Текстильные дорожки одного цвета для прямоугольных или круглых столов.",
    city: "Ташкент",
    priceFrom: 850_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/decor-table.jpg",
  }),
  currentSeedOffer({
    id: "service-gulzor-table-numbers",
    sku: "MR-MKT-016",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Номера столов и карточки гостей",
    description: "Нумерация десяти столов и 100 именных карточек в едином дизайне.",
    city: "Ташкент",
    priceFrom: 650_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/table-roses.jpg",
  }),
  currentSeedOffer({
    id: "service-gulzor-welcome-sign",
    sku: "MR-MKT-017",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Приветственная табличка на вход",
    description: "Макет с именами и датой, печать на плотной основе и подставка.",
    city: "Ташкент",
    priceFrom: 550_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
  }),
  currentSeedOffer({
    id: "service-gulzor-minimal-invitations",
    sku: "MR-MKT-018",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Лаконичные приглашения, 30 штук",
    description: "Готовый макет, печать имён и конверты без сложного декоративного оформления.",
    city: "Ташкент",
    priceFrom: 420_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/invitations.jpg",
  }),
  currentSeedOffer({
    id: "service-gulzor-favor-boxes",
    sku: "MR-MKT-019",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Коробочки для подарков гостям, 50 штук",
    description: "Плотные коробочки с лентой и персональной наклейкой; наполнение не входит.",
    city: "Ташкент",
    priceFrom: 700_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/gift-boxes.jpg",
  }),
  currentSeedOffer({
    id: "service-fergana-tea-gifts",
    sku: "MR-MKT-020",
    supplierId: "supplier-fergana-party",
    categoryId: "cat-gifts-print",
    title: "Подарочный набор с чаем и сладостями",
    description: "Чай, шоколад, декоративная композиция и подарочная коробка с доставкой по городу.",
    city: "Фергана",
    priceFrom: 350_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    imageUrl: "/catalog/photos/market-gift-box.jpg",
  }),
  currentSeedOffer({
    id: "service-shirin-two-tier-cake",
    sku: "MR-MKT-021",
    supplierId: "supplier-shirin",
    categoryId: "cat-cakes",
    title: "Двухъярусный свадебный торт",
    description: "Две начинки, ровное покрытие, простой живой декор и безопасная доставка.",
    city: "Ташкент",
    priceFrom: 210_000,
    priceUnit: "за килограмм",
    offerKind: "sale",
    imageUrl: "/catalog/photos/cake.jpg",
  }),
  currentSeedOffer({
    id: "service-shirin-cupcakes",
    sku: "MR-MKT-022",
    supplierId: "supplier-shirin",
    categoryId: "cat-cakes",
    title: "Капкейки для 24 гостей",
    description: "Две начинки, кремовое оформление в цветах события и коробки для перевозки.",
    city: "Ташкент",
    priceFrom: 720_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/candy-balloons.jpg",
  }),
  currentSeedOffer({
    id: "service-fergana-tableware-set",
    sku: "MR-MKT-023",
    supplierId: "supplier-fergana-party",
    categoryId: "cat-tableware",
    title: "Сервировочный набор на 30 гостей",
    description: "Тарелки, приборы, бокалы, салфетки и расходные материалы для самостоятельного праздника.",
    city: "Фергана",
    priceFrom: 1_350_000,
    priceUnit: "за набор",
    offerKind: "sale",
    imageUrl: "/catalog/photos/tableware.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-compact-sound",
    sku: "MR-EQP-012",
    supplierId: "supplier-prostage",
    categoryId: "cat-sound-light",
    title: "Компактный звук до 50 гостей",
    description: "Активная колонка, стойка, микрофон и кабели с проверкой перед выдачей.",
    city: "Ташкент",
    priceFrom: 250_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/wireless-speaker.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-sound-200",
    sku: "MR-EQP-013",
    supplierId: "supplier-prostage",
    categoryId: "cat-sound-light",
    title: "Звуковой комплект до 200 гостей",
    description: "Четыре колонки, сабвуферы, микшер, два микрофона, доставка и настройка.",
    city: "Ташкент",
    priceFrom: 2_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/market-audio-kit.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-digital-mixer",
    sku: "MR-EQP-014",
    supplierId: "supplier-prostage",
    categoryId: "cat-sound-light",
    title: "Цифровой аудиомикшер",
    description: "Многоканальный пульт, цифровой стейджбокс, кабели и сохранение настроек события.",
    city: "Ташкент",
    priceFrom: 700_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/audio-mixer.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-speaker-pair",
    sku: "MR-EQP-015",
    supplierId: "supplier-prostage",
    categoryId: "cat-sound-light",
    title: "Пара активных колонок со стойками",
    description: "Две колонки, стойки, соединительные кабели и базовая консультация по подключению.",
    city: "Ташкент",
    priceFrom: 500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/wireless-speaker.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-lapel-mics",
    sku: "MR-EQP-016",
    supplierId: "supplier-prostage",
    categoryId: "cat-sound-light",
    title: "Два беспроводных петличных микрофона",
    description: "Два передатчика, приёмник, крепления, запасные элементы питания и проверка связи.",
    city: "Ташкент",
    priceFrom: 300_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/wireless-lapel.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-bright-projector",
    sku: "MR-EQP-017",
    supplierId: "supplier-prostage",
    categoryId: "cat-screens-stage",
    title: "Проектор 5000 люмен и экран",
    description: "Яркий проектор, экран, стойка, HDMI-комплект и настройка для конференционного зала.",
    city: "Ташкент",
    priceFrom: 800_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/projector-room.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-tv-panel",
    sku: "MR-EQP-018",
    supplierId: "supplier-prostage",
    categoryId: "cat-screens-stage",
    title: "Телевизор 75 дюймов на стойке",
    description: "Экран, напольная стойка, кабели, доставка и проверка презентации перед началом.",
    city: "Ташкент",
    priceFrom: 900_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/conference-presentation.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-outdoor-led",
    sku: "MR-EQP-019",
    supplierId: "supplier-prostage",
    categoryId: "cat-screens-stage",
    title: "Уличный LED-экран 4 × 3 метра",
    description: "Экран, несущая конструкция, видеопроцессор, монтаж и технический специалист.",
    city: "Ташкент",
    priceFrom: 6_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/led-stage.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-moving-lights",
    sku: "MR-EQP-020",
    supplierId: "supplier-prostage",
    categoryId: "cat-sound-light",
    title: "Комплект поворотного сценического света",
    description: "Четыре прибора, стойки или подвес, контроллер и базовая световая программа.",
    city: "Ташкент",
    priceFrom: 1_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/led-stage.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-smoke-machine",
    sku: "MR-EQP-021",
    supplierId: "supplier-prostage",
    categoryId: "cat-power-effects",
    title: "Дым-машина для сцены",
    description: "Компактная дым-машина, безопасная жидкость, пульт и инструктаж перед использованием.",
    city: "Ташкент",
    priceFrom: 300_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/stage.jpg",
  }),
  currentSeedOffer({
    id: "service-prostage-generator",
    sku: "MR-EQP-022",
    supplierId: "supplier-prostage",
    categoryId: "cat-power-effects",
    title: "Резервный генератор для площадки",
    description: "Генератор, силовые кабели, доставка и проверка нагрузки до начала мероприятия.",
    city: "Ташкент",
    priceFrom: 900_000,
    priceUnit: "за день",
    offerKind: "rental",
    imageUrl: "/catalog/photos/audio-engineer.jpg",
  }),
  currentSeedOffer({
    id: "service-sahna-tent-furniture-100",
    sku: "MR-EQP-023",
    supplierId: "supplier-sahna",
    categoryId: "cat-event-rental",
    title: "Шатёр, столы и стулья на 100 гостей",
    description: "Навес, десять столов, 100 стульев, доставка, монтаж и сбор после события.",
    city: "Ташкент",
    priceFrom: 6_500_000,
    priceUnit: "за комплект",
    offerKind: "rental",
    imageUrl: "/catalog/photos/event-tent.jpg",
  }),
];
