import type {
  CatalogSection,
  DemoRequest,
  DemoRole,
  ModerationItem,
  OfferKind,
  Service,
  ServiceCategory,
  Supplier,
} from "@/lib/types";

export const catalogSections: Array<{
  id: CatalogSection;
  name: string;
  icon: string;
  description: string;
}> = [
  { id: "services", name: "Услуги", icon: "✦", description: "Площадки, еда, съёмка, оформление и организация" },
  { id: "market", name: "Маркет", icon: "◇", description: "Цветы, декор, подарки и нужные для события мелочи" },
  { id: "equipment", name: "Техника", icon: "▣", description: "Звук, свет, экраны, аренда и технические специалисты" },
];

export const offerKindLabels: Record<OfferKind, string> = {
  service: "Услуга",
  sale: "Покупка",
  rental: "Аренда",
};

export const categories: ServiceCategory[] = [
  { id: "cat-venue", slug: "venue", name: "Площадки", icon: "⌂", section: "services", requiredForWedding: true },
  { id: "cat-catering", slug: "catering", name: "Кейтеринг", icon: "◉", section: "services", requiredForWedding: true },
  { id: "cat-photo", slug: "photo-video", name: "Фото и видео", icon: "▣", section: "services", requiredForWedding: true },
  { id: "cat-decor", slug: "decor", name: "Оформление и флористика", icon: "✦", section: "services", requiredForWedding: true },
  { id: "cat-host", slug: "host", name: "Ведущие и развлечения", icon: "◍", section: "services", requiredForWedding: true },
  { id: "cat-music", slug: "music", name: "Музыка и DJ", icon: "♫", section: "services", requiredForWedding: true },
  { id: "cat-transport", slug: "transport", name: "Транспорт", icon: "◇", section: "services", requiredForWedding: false },
  { id: "cat-training", slug: "training", name: "Тренинги и тимбилдинг", icon: "△", section: "services", requiredForWedding: false },
  { id: "cat-flowers", slug: "flowers", name: "Цветы и букеты", icon: "❀", section: "market", requiredForWedding: false },
  { id: "cat-event-details", slug: "event-details", name: "Декор и праздничные мелочи", icon: "♡", section: "market", requiredForWedding: false },
  { id: "cat-gifts-print", slug: "gifts-print", name: "Подарки и полиграфия", icon: "▱", section: "market", requiredForWedding: false },
  { id: "cat-sound-light", slug: "sound-light", name: "Звук и свет", icon: "◐", section: "equipment", requiredForWedding: false },
  { id: "cat-screens-stage", slug: "screens-stage", name: "Экраны и сцены", icon: "▤", section: "equipment", requiredForWedding: false },
];

export const suppliers: Supplier[] = [
  {
    id: "supplier-silk-road",
    slug: "silk-road-events",
    name: "Silk Road Events",
    city: "Ташкент",
    description: "Банкетная площадка и координация камерных и больших свадеб.",
    verified: true,
    verificationLabel: "Компания проверена модератором",
    updatedAt: "2026-08-31T09:30:00+05:00",
    responseMedianMinutes: 38,
    responseSampleSize: 12,
    portfolio: ["Свадьба на 120 гостей", "Никах и семейный ужин", "Корпоративная конференция"],
  },
  {
    id: "supplier-nur-photo",
    slug: "nur-photo-film",
    name: "Nur Photo & Film",
    city: "Ташкент",
    description: "Фото- и видеосъёмка свадеб, семейных событий и деловых мероприятий.",
    verified: true,
    verificationLabel: "Личность и портфолио проверены",
    updatedAt: "2026-08-28T16:10:00+05:00",
    responseMedianMinutes: 74,
    responseSampleSize: 8,
    portfolio: ["Wedding story", "Love story", "Business highlights"],
  },
  {
    id: "supplier-sabo-decor",
    slug: "sabo-decor",
    name: "Sabo Decor",
    city: "Самарканд",
    description: "Современный декор, флористика и оформление фотозон.",
    verified: false,
    verificationLabel: "Проверка поставщика не завершена",
    updatedAt: "2026-06-12T11:00:00+05:00",
    responseMedianMinutes: null,
    responseSampleSize: 2,
    portfolio: ["Garden wedding", "Национальная церемония"],
  },
  {
    id: "supplier-teamcraft",
    slug: "teamcraft-uz",
    name: "TeamCraft UZ",
    city: "Ташкент",
    description: "Фасилитация, тренинги и командные программы для компаний.",
    verified: true,
    verificationLabel: "Компания проверена модератором",
    updatedAt: "2026-08-30T13:45:00+05:00",
    responseMedianMinutes: 51,
    responseSampleSize: 6,
    portfolio: ["Outdoor team day", "Leadership lab", "Стратегическая сессия"],
  },
  {
    id: "supplier-gulzor",
    slug: "gulzor-market",
    name: "Gulzor Market",
    city: "Ташкент",
    description: "Цветы, наборы декора и полиграфия для свадеб и семейных праздников.",
    verified: true,
    verificationLabel: "Магазин проверен модератором",
    updatedAt: "2026-09-01T12:20:00+05:00",
    responseMedianMinutes: 29,
    responseSampleSize: 15,
    portfolio: ["Свадебные букеты", "Декор для столов", "Именные приглашения"],
  },
  {
    id: "supplier-ovoza-tech",
    slug: "ovoza-tech",
    name: "Ovoza Tech",
    city: "Ташкент",
    description: "Аренда, продажа и техническое сопровождение звука, света и экранов.",
    verified: true,
    verificationLabel: "Компания и оборудование проверены",
    updatedAt: "2026-09-01T15:10:00+05:00",
    responseMedianMinutes: 42,
    responseSampleSize: 9,
    portfolio: ["Свет для свадебной сцены", "LED-экран для конференции", "Звук для тимбилдинга"],
  },
];

export const services: Service[] = [
  {
    id: "service-silk-hall",
    supplierId: "supplier-silk-road",
    categoryId: "cat-venue",
    title: "Банкетный зал Silk Hall",
    description: "Зал до 180 гостей, базовая мебель, сцена и парковка.",
    city: "Ташкент",
    priceFrom: 18_000_000,
    priceUnit: "за день",
    offerKind: "service",
    active: true,
    published: true,
    updatedAt: "2026-08-31T09:30:00+05:00",
    availabilityConfirmedAt: "2026-08-31T09:30:00+05:00",
  },
  {
    id: "service-silk-catering",
    supplierId: "supplier-silk-road",
    categoryId: "cat-catering",
    title: "Свадебный кейтеринг",
    description: "Меню узбекской и европейской кухни, обслуживание и сервировка.",
    city: "Ташкент",
    priceFrom: 240_000,
    priceUnit: "за гостя",
    offerKind: "service",
    active: true,
    published: true,
    updatedAt: "2026-08-31T09:30:00+05:00",
    availabilityConfirmedAt: "2026-08-31T09:30:00+05:00",
  },
  {
    id: "service-nur-wedding",
    supplierId: "supplier-nur-photo",
    categoryId: "cat-photo",
    title: "Фото + видео полного свадебного дня",
    description: "Два оператора, фотограф, короткий ролик и полный фильм.",
    city: "Ташкент",
    priceFrom: 8_500_000,
    priceUnit: "за услугу",
    offerKind: "service",
    active: true,
    published: true,
    updatedAt: "2026-08-28T16:10:00+05:00",
    availabilityConfirmedAt: "2026-08-28T16:10:00+05:00",
  },
  {
    id: "service-sabo-garden",
    supplierId: "supplier-sabo-decor",
    categoryId: "cat-decor",
    title: "Оформление Garden Wedding",
    description: "Концепция, президиум, флористика и фотозона.",
    city: "Самарканд",
    priceFrom: 12_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    active: true,
    published: true,
    updatedAt: "2026-06-12T11:00:00+05:00",
    availabilityConfirmedAt: null,
  },
  {
    id: "service-teamcraft-day",
    supplierId: "supplier-teamcraft",
    categoryId: "cat-training",
    title: "Командный день под ключ",
    description: "Диагностика запроса, сценарий, два фасилитатора и разбор результатов.",
    city: "Ташкент",
    priceFrom: 14_000_000,
    priceUnit: "за услугу",
    offerKind: "service",
    active: true,
    published: true,
    updatedAt: "2026-08-30T13:45:00+05:00",
    availabilityConfirmedAt: "2026-08-30T13:45:00+05:00",
  },
  {
    id: "service-gulzor-bouquet",
    supplierId: "supplier-gulzor",
    categoryId: "cat-flowers",
    title: "Свадебный букет из сезонных цветов",
    description: "Букет невесты в выбранной гамме, лента и упаковка для перевозки.",
    city: "Ташкент",
    priceFrom: 650_000,
    priceUnit: "за штуку",
    offerKind: "sale",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-gulzor-candles",
    supplierId: "supplier-gulzor",
    categoryId: "cat-event-details",
    title: "Набор свечей и подсвечников для столов",
    description: "Готовый набор для оформления пяти гостевых столов в тёплой гамме.",
    city: "Ташкент",
    priceFrom: 480_000,
    priceUnit: "за набор",
    offerKind: "sale",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-gulzor-invitations",
    supplierId: "supplier-gulzor",
    categoryId: "cat-gifts-print",
    title: "Именные приглашения, 50 штук",
    description: "Дизайн, печать и конверты; текст согласуется до запуска в производство.",
    city: "Ташкент",
    priceFrom: 900_000,
    priceUnit: "за набор",
    offerKind: "sale",
    active: true,
    published: true,
    updatedAt: "2026-09-01T12:20:00+05:00",
    availabilityConfirmedAt: "2026-09-01T12:20:00+05:00",
  },
  {
    id: "service-ovoza-sound",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Комплект звука и света для зала",
    description: "Колонки, микрофоны, световые приборы, доставка и настройка перед событием.",
    city: "Ташкент",
    priceFrom: 4_500_000,
    priceUnit: "за день",
    offerKind: "rental",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-led",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-screens-stage",
    title: "LED-экран с установкой",
    description: "Экран подходящего размера, доставка, монтаж, проверка и демонтаж после события.",
    city: "Ташкент",
    priceFrom: 7_000_000,
    priceUnit: "за день",
    offerKind: "rental",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-engineer",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Технический специалист на мероприятие",
    description: "Настройка оборудования и контроль звука и света во время программы.",
    city: "Ташкент",
    priceFrom: 1_600_000,
    priceUnit: "за услугу",
    offerKind: "service",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
  {
    id: "service-ovoza-garland",
    supplierId: "supplier-ovoza-tech",
    categoryId: "cat-sound-light",
    title: "Гирлянда тёплого света, 20 метров",
    description: "Соединяемая уличная гирлянда для фотозоны, навеса или небольшого зала.",
    city: "Ташкент",
    priceFrom: 780_000,
    priceUnit: "за комплект",
    offerKind: "sale",
    active: true,
    published: true,
    updatedAt: "2026-09-01T15:10:00+05:00",
    availabilityConfirmedAt: "2026-09-01T15:10:00+05:00",
  },
];

export const seededRequests: DemoRequest[] = [
  {
    id: "request-demo-1",
    clientName: "Алина",
    clientPhone: "+998 90 123 45 67",
    supplierId: "supplier-silk-road",
    serviceId: "service-silk-hall",
    eventType: "Свадьба",
    eventDate: "2026-10-18",
    city: "Ташкент",
    guestCount: 120,
    budget: 25_000_000,
    message: "Нужен зал и информация по свободным датам, меню обсудим отдельно.",
    status: "submitted",
    createdAt: "2026-09-01T18:20:00+05:00",
    firstViewedAt: null,
    firstRespondedAt: null,
  },
];

export const seededModeration: ModerationItem[] = [
  {
    id: "moderation-sabo",
    serviceId: "service-sabo-garden",
    supplierId: "supplier-sabo-decor",
    reason: "Нужно подтвердить актуальность цены и доступность календаря.",
    status: "pending",
    updatedAt: "2026-09-01T10:00:00+05:00",
  },
];

export const demoAccounts: Array<{
  email: string;
  password: string;
  name: string;
  role: DemoRole;
  description: string;
}> = [
  { email: "client@marosim.local", password: "Marosim-Local-2026!", name: "Клиент", role: "client", description: "Ищет предложения и отправляет заявки" },
  { email: "planner@marosim.local", password: "Marosim-Local-2026!", name: "Организатор", role: "client_planner", description: "Собирает план события и бюджет" },
  { email: "supplier@marosim.local", password: "Marosim-Local-2026!", name: "Поставщик", role: "supplier", description: "Управляет предложениями и заявками" },
  { email: "supplier-planner@marosim.local", password: "Marosim-Local-2026!", name: "Координатор поставщика", role: "supplier_planner", description: "Следит за загрузкой и ответами" },
  { email: "admin@marosim.local", password: "Marosim-Local-2026!", name: "Администратор", role: "admin", description: "Модерирует каталог и блокировки" },
];

export function getSupplierById(id: string) {
  return suppliers.find((supplier) => supplier.id === id);
}

export function getServiceById(id: string) {
  return services.find((service) => service.id === id);
}

export function getCategoryById(id: string) {
  return categories.find((category) => category.id === id);
}
